import cors from "cors";
import express from "express";
import servicesRouter from "./routers/services";
import authRouter from "./routers/auth";
import speciesRouter from "./routers/species";
import breedRouter from "./routers/breed";
import petRouter from "./routers/pet";
import pethouseRouter from "./routers/pethouse";
import roleRouter from "./routers/role";
import statusRouter from "./routers/status_appointment";
import contactRouter from "./routers/contact";
import aboutRouter from "./routers/about";
import newsRouter from "./routers/news";
import reviewRouter from "./routers/reviews";
import appointmentRouter from "./routers/appointments";
import userRouter from "./routers/User";
import setTimeRouter from "./routers/setTime";
import staffRouter from "./routers/staff";
import imageRouter from "./routers/uploadImage";
import statusContactRouter from "./routers/status_contact";
import shiftWorkRouter from "./routers/shift_work";
import menuRouter from "./routers/menu";
import statusOrderRouter from "./routers/stauts_order";
import category from "./routers/category";
import products from "./routers/products";
import carts from "./routers/carts";
import order from "./routers/order";
import statusPet from "./routers/status_pet";
import vnpayRoutes from "./routers/vnpayRoutes";
import dashboardRoutes from "./routers/dashboard";
import bannerRouter from "./routers/banner";
import PrintInvoice from "./routers/PrintInvoice";
import menuTypeRoutes from "./routers/menuTYpe";
import websiteInformationRoutes from "./routers/websiteInformation";
import paymentMethodsRoutes from "./routers/paymentMethods";
import deliveryAddressRoutes from "./routers/deliveryAddress";
import statusPaymentRouters from "./routers/statusPayment";
import footerRouters from "./routers/footer";
import messageRouter from "./routers/message";
const app = express();
app.use(express.json());
app.use(cors());

app.use("/api", messageRouter);
app.use("/api", bannerRouter);
app.use("/api", servicesRouter);
app.use("/api", authRouter);
app.use("/api", speciesRouter);
app.use("/api", petRouter);
app.use("/api", breedRouter);
app.use("/api", pethouseRouter);
app.use("/api", roleRouter);
app.use("/api", statusRouter);
app.use("/api", contactRouter);
app.use("/api", aboutRouter);
app.use("/api", newsRouter);
app.use("/api", reviewRouter);
app.use("/api", appointmentRouter);
app.use("/api", userRouter);
app.use("/api", setTimeRouter);
app.use("/api", staffRouter);
app.use("/api", imageRouter);
app.use("/api", statusContactRouter);
app.use("/api", shiftWorkRouter);
app.use("/api", menuRouter);
app.use("/api", statusOrderRouter);
app.use("/api", category);
app.use("/api", products);
app.use("/api", carts);
app.use("/api", order);
app.use("/api", statusPet);
app.use("/api", vnpayRoutes);
app.use("/api", dashboardRoutes);
app.use("/api", PrintInvoice);
app.use("/api", menuTypeRoutes);
app.use("/api", websiteInformationRoutes);
app.use("/api", paymentMethodsRoutes);
app.use("/api", statusPaymentRouters);
app.use("/api", deliveryAddressRoutes);
app.use("/api", footerRouters);

export const viteNodeApp = app;
